apiVersion: v1
kind: Secret
metadata:
  name: cob-secrets
stringData:
  .env: |
    GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
    GLUSERNAME=$GLUSERNAME
    GLTOKEN=$GLTOKEN
    GLREGISTRY=$GLREGISTRY
    HELM_CHART_NAME=$HELM_CHART_NAME
    HELM_REPO_NAME=$HELM_REPO_NAME
    HELM_REPO_URL=$HELM_REPO_URL
    HELM_REPO_USERNAME=$HELM_REPO_USERNAME
    HELM_REPO_PASSWORD=$HELM_REPO_PASSWORD
    AMQP_HOSTNAME=$AMQP_HOSTNAME
    AMQP_USERNAME=$AMQP_USERNAME
    AMQP_PASSWORD=$AMQP_PASSWORD
    MONGODB_HOSTNAME=$MONGODB_HOSTNAME
    MONGODB_USERNAME=$MONGODB_USERNAME
    MONGODB_PASSWORD=$MONGODB_PASSWORD
    SMTP_API_KEY=$SMTP_API_KEY
    BUCKET_NAME=$BUCKET_NAME
    PLATFORM_USERNAME=$PLATFORM_USERNAME
    PLATFORM_PASSWORD=$PLATFORM_PASSWORD
  challenge-bucket-key.json: |
    $CHALLENGE_BUCKET_KEY
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker-registry-credentials
data:
  .dockerconfigjson: $DOCKER_REGISTRY_CREDENTIALS
  .dockerconfig.json: $DOCKER_REGISTRY_CREDENTIALS
